### ISSUE TITLE
Exception while returning results

### ISSUE THREAD

**Issue by AhmadIzaz** [AhsanMunir/Google-Places-SDK-for-Android#3]
W/Filter: An exception occured during performFiltering()!
    java.lang.ClassCastException: com.google.android.libraries.places.internal.hm cannot be cast to java.util.ArrayList
        at com.a.v.adatpters.AutoCompleteAdapter.getAutocomplete(AutoCompleteAdapter.java:152)
        at com.a.v.adatpters.AutoCompleteAdapter.access$000(AutoCompleteAdapter.java:28)
        at com.a.v.adatpters.AutoCompleteAdapter$1.performFiltering(AutoCompleteAdapter.java:81)
        at android.widget.Filter$RequestHandler.handleMessage(Filter.java:234)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by LeojAngelico** [comment]
I got this error too. any solution?

**Comment by AhmadIzaz** [comment]
@LeojAngelico I will suggest you to have a look at below link and try to do it on your own instead on depending on this library.
https://developers.google.com/places/android-sdk/autocomplete

**Comment by aliraza96** [comment]
Have anyone solved this issue yet?? Kindly reply

**Comment by ggn22g** [comment]
> I got this error too. any solution?

I have changed the ArrayList to List in response and Adapter. Now it's working.
